// Generated by antelope-abi2rs 0.4.1 - eosio::abi/1.2

use serde::{Deserialize, Deserializer, Serialize};

type Name = String;
type Bytes = String;

macro_rules! impl_try_from_str {
    ($type:ty) => {
        impl TryFrom<&str> for $type {
            type Error = serde_json::Error;
            #[inline]
            fn try_from(str: &str) -> Result<Self, Self::Error> {
                serde_json::from_str(str)
            }
        }
    };
}

#[derive(Serialize, Deserialize, Debug, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Setabi {
    pub account: Name,
    pub abi: Bytes,
}
impl_try_from_str!(Setabi);
